### ISSUE TITLE
Add a favourite Alko

### ISSUE THREAD

**Issue by eerokar** [AlcoNavigations/Alkompassi#17]
#### Scenario
User wants to add Alko to Favorites for later use. This must be stored into a device database so the data will persist.

#### Acceptance criteria
Room database for locations is created(@Database, @Entity, @Dao), Successful saving to the room database with proper error handling.

#### • Additional info
Room Database

**Comment by ahlstronomi** [comment]
The necessary Room objects are created. Saving should work when saving comes possible from the UI
