### ISSUE TITLE
Browse favourite Alkos

### ISSUE THREAD

**Issue by eerokar** [AlcoNavigations/Alkompassi#18]
#### Scenario
User wants to browse favourite alkos. This list is located in the same bottomsheet as the nearest Alkos

#### Acceptance criteria
Fetch favorites from the database. Populate the RecyclerView of the favourite Alkos

#### • Additional info
Room Database

**Comment by ahlstronomi** [comment]
This will be done by navigating to a another fragment that updates the activities views.

**Comment by ahlstronomi** [comment]
Done
