### ISSUE TITLE
Icons too small, pls fix devs

### ISSUE THREAD

**Issue by ErkHal** [AlcoNavigations/Alkompassi#23]
When selecting an Alko from the map, the appearing routing and Maps icons are way too small and in a weird position. Pls fix, need this app to help me with my fresh career as a full-bottle alcoholism developer.

**Comment by ahlstronomi** [comment]
We have planned to implement fabs to replace the defalut gmaps intent buttons of the mapview. Thanks for the feedback @ErkHal, PR:s welcome!

**Comment by ahlstronomi** [comment]
Done
