### ISSUE TITLE
Get Alko location data

### ISSUE THREAD

**Issue by eerokar** [AlcoNavigations/Alkompassi#3]
#### Scenario
User wants to see Alkos on a map. The location data must be fetched from the gmaps api

#### Acceptance criteria
Location data is fetched successfully from the maps API and printed to the Logcat with proper error handling

#### Additional info
[Google maps documentation](https://developers.google.com/places/web-service/search)

[Single place info](https://developers.google.com/places/web-service/details)

**Comment by ahlstronomi** [comment]
Done
